version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/readrealm
      SPRING_DATASOURCE_USERNAME: localuser
      SPRING_DATASOURCE_PASSWORD: localpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: readrealm
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
